# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='silly',
            field=models.BooleanField(default=False),
        ),
    ]
