# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_silly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='silly',
        ),
    ]
