# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_snippet_silly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='langauge',
            new_name='language',
        ),
    ]
